version: "3"
services:
  mongo:
    image: mongo:3.4.4

  subscription-api:
    image: rezme/resume-subscription-api:v0.0.1
    environment:
      - APP_PORT=80
      - MONGO_URI=mongodb://mongo/subscrition
    volumes:
      - /var/lib/mongo/db/subscription
    depends_on:
      - mongo

  token-api:
    image: rezme/resume-token-api:v0.1.0
    environment:
      - APP_PORT=80
      - JWT_SECRET=foo_bar
      - JWT_EXPIRES_IN=60
    volumes:
      - /var/lib/mongo/db/tokens
    depends_on:
      - mongo

  core-api:
    image: rezme/resume-core-api:v0.0.1
    environment:
      - APP_PORT=80
      - MONGO_URI=mongodb://mongo/resume
      - JWT_TOKEN_HEADER=x-jwt-token
      - JWT_SECRET=foo_bar
    volumes:
      - /var/lib/mongo/db/resume
    depends_on:
      - mongo

  proxy-api:
    image: rezme/resume-proxy-api
    build:
      context: .
    ports:
      - 80:80
    links:
      - core-api
      - subscription-api
      - token-api
